== Vert.x Common SQL interface

The common SQL interface is used to interact with Vert.x SQL services.

You obtain a connection to the database via the service interface for the specific SQL service that you are using
(e.g. JDBC/MySQL/PostgreSQL).

== The SQL Connection

A connection to the database is represented by `link:jsdoc/sql_connection-SqlConnection.html[SqlConnection]`.

=== Auto-commit

When you obtain a connection auto commit is set to `true`. This means that each operation you perform will effectively
execute in its own transaction.

If you wish to perform multiple operations in a single transaction you should set auto commit to false with
`link:jsdoc/sql_connection-SqlConnection.html#setAutoCommit[setAutoCommit]`.

When the operation is complete, the handler will be called:

[source,java]
----
connection.setAutoCommit(false, function (res, res_err) {
  if ((res != null)) {
  } else {
  };
});

----

=== Executing queries

To execute a query use `link:jsdoc/sql_connection-SqlConnection.html#query[query]`

The query string is raw SQL that is passed through without changes to the actual database.

The handler will be called with the results, represented by `link:dataobject/ResultSet.html[ResultSet]` when the query has
been run.

[source,java]
----
connection.query("SELECT ID, FNAME, LNAME, SHOE_SIZE from PEOPLE", function (res, res_err) {
  if ((res != null)) {
    // Get the result set
    var resultSet = res;
  } else {
  };
});

----

The `link:dataobject/ResultSet.html[ResultSet]` instance represents the results of a query.

The list of column names are available with `link:dataobject/ResultSet.html#getColumnNames[getColumnNames]`, and the actual results
available with `link:dataobject/ResultSet.html#getResults[getResults]`

The results are a list of `link:jsdoc/json_array-JsonArray.html[JsonArray]` instances, one for each row of the results.

[source,java]
----

var columnNames = resultSet.columnNames;

var results = resultSet.results;

Array.prototype.forEach.call(results, function(row) {

  var id = row.getString(0);
  var fName = row.getString(1);
  var lName = row.getString(2);
  var shoeSize = row.getInteger(3);

});


----

You can also retrieve the rows as a list of Json object instances with `link:dataobject/ResultSet.html#getRows[getRows]` -
this can give you a somewhat simpler API to work with, but please be aware that SQL results can contain duplicate
column names - if that's the case you should use `link:dataobject/ResultSet.html#getResults[getResults]` instead.

Here's an example of iterating through the results as Json object instances:

[source,java]
----

var rows = resultSet.rows;

Array.prototype.forEach.call(rows, function(row) {

  var id = row."ID";
  var fName = row."FNAME";
  var lName = row."LNAME";
  var shoeSize = row."SHOE_SIZE";

});


----

=== Prepared statement queries

To execute a prepared statement query you can use
`link:jsdoc/sql_connection-SqlConnection.html#queryWithParams[queryWithParams]`.

This takes the query, containing the parameter place holders, and a `link:jsdoc/json_array-JsonArray.html[JsonArray]` or parameter
values.

[source,java]
----

var query = "SELECT ID, FNAME, LNAME, SHOE_SIZE from PEOPLE WHERE LNAME=? AND SHOE_SIZE > ?";
var params = [
  "Fox",
  9
];

connection.queryWithParams(query, params, function (res, res_err) {

  if ((res != null)) {
    // Get the result set
    var resultSet = res;
  } else {
  };
});


----

=== Executing INSERT, UPDATE or DELETE

To execute an operation which updates the database use `link:jsdoc/sql_connection-SqlConnection.html#update[update]`.

The update string is raw SQL that is passed through without changes to the actual database.

The handler will be called with the results, represented by `link:dataobject/UpdateResult.html[UpdateResult]` when the update has
been run.

The update result holds the number of rows updated with `link:dataobject/UpdateResult.html#getUpdated[getUpdated]`, and
if the update generated keys, they are available with `link:dataobject/UpdateResult.html#getKeys[getKeys]`.

[source,java]
----

var columnNames = resultSet.columnNames;

var results = resultSet.results;

Array.prototype.forEach.call(results, function(row) {

  var id = row.getString(0);
  var fName = row.getString(1);
  var lName = row.getString(2);
  var shoeSize = row.getInteger(3);

});


----

=== Prepared statement updates

To execute a prepared statement update you can use
`link:jsdoc/sql_connection-SqlConnection.html#updateWithParams[updateWithParams]`.

This takes the update, containing the parameter place holders, and a `link:jsdoc/json_array-JsonArray.html[JsonArray]` or parameter
values.

[source,java]
----

var update = "UPDATE PEOPLE SET SHOE_SIZE = 10 WHERE LNAME=?";
var params = [
  "Fox"
];

connection.updateWithParams(update, params, function (res, res_err) {

  if ((res != null)) {

    var updateResult = res;

    console.log("No. of rows updated: " + updateResult.updated);

  } else {
  };
});


----

=== Executing other operations

To execute any other database operation, e.g. a `CREATE TABLE` you can use
`link:jsdoc/sql_connection-SqlConnection.html#execute[execute]`.

The string is passed through without changes to the actual database. The handler is called when the operation
is complete

[source,java]
----

var sql = "CREATE TABLE PEOPLE (ID int generated by default as identity (start with 1 increment by 1) not null,FNAME varchar(255), LNAME varchar(255), SHOE_SIZE int);";

connection.execute(sql, function (execute, execute_err) {
  if ((execute != null)) {
    console.log("Table created !");
  } else {
  };
});


----

=== Using transactions

To use transactions first set auto-commit to false with `link:jsdoc/sql_connection-SqlConnection.html#setAutoCommit[setAutoCommit]`.

You then do your transactional operations and when you want to commit or rollback use
`link:jsdoc/sql_connection-SqlConnection.html#commit[commit]` or
`link:jsdoc/sql_connection-SqlConnection.html#rollback[rollback]`.

Once the commit/rollback is complete the handler will be called and the next transaction will be automatically started.

[source,java]
----

// Do stuff with connection - updates etc

// Now commit

connection.commit(function (res, res_err) {
  if ((res != null)) {
  } else {
  };
});


----

=== Closing connections

When you've done with the connection you should return it to the pool with `link:jsdoc/sql_connection-SqlConnection.html#close[close]`.